import { envConfig } from "./envConfig.js";
import swaggerAutogen from "swagger-autogen";

const doc = {
  info: {
    title: "RAC API",
    description: "API Documentation generated by swagger-autogen",
    version: "1.0.0",
  },
  host: `${envConfig.HOST}:${envConfig.PORT}`,
  basePath: "/",
  schemes: ["http"],
  securityDefinitions: {
    bearerAuth: {
      type: "apiKey",
      in: "header",
      name: "Authorization",
      description:
        "Enter your bearer token in the format **Bearer &lt;token>**",
    },
  },
};

const outputFile = `../../docs/api-spec.json`;

// Pointing to server.ts because all endpoints are mounted there.
const endpointsFiles = ["../server.ts"];

// Generate swagger.json
swaggerAutogen()(outputFile, endpointsFiles, doc).then(() => {
  console.log(
    `📄 Swagger documentation generated successfully at ${outputFile}`,
  );
});
